name: ServerAnalytics
version: 0.0.1
main: me.reratos.serveranalytics.ServerAnalytics
author: Relry
database: true
#website: https://www.spigotmc.org/resources/timehandler.83803/
#description: >
#  It allows manipulating the time of the worlds and / or setting a condition for it.

#commands:
#  analytics: